### PR TITLE
fixed sidebar styles!

### PR DESCRIPTION
**Pull request by jacquelynfambrough**
changed underscore for body and title classnames to dash to fix problem!

### CODE REVIEW

**Comment by bgveenstra** [comment]
@jacquelynfambrough Probably not necessary to make 3 commits for this change, but great job fixing the issue!  Ready to merge 👍

**Comment by bgveenstra** [comment]
Also in future pull requests please mention the issue you are fixing (#1)

**Comment by tgaff** [comment]
@jacquelynfambrough  This was good to merge, but now you've added more code to it.  I can't accept it with irrelevant changes in it :-(

**Pull request closed without merging**
